research_company_task:
  description: >
    Conduci una ricerca approfondita su {company}, iniziando con informazioni generali sull'azienda e poi concentrandoti sulle loro attività in {country}:

    1. Prima, cerca di trovare il sito web ufficiale dell'azienda e informazioni di base su cosa fanno
    2. Ricerca il background, i servizi e le offerte dell'azienda SENZA restrizioni geografiche
    3. POI concentrati sulle loro operazioni in {country}
    4. Cerca notizie recenti, sviluppi degli ultimi 12-24 mesi
    5. Identifica le tendenze del settore relative al loro campo in {country}

    Usa un approccio graduale:
    - Inizia con ricerche ampie solo sul nome dell'azienda
    - Poi aggiungi dettagli sul loro settore di attività se noto
    - Infine aggiungi informazioni specifiche sul paese

    Se le informazioni dirette sull'azienda in {country} sono limitate, fornisci comunque le informazioni generali sull'azienda e poi discuti le tendenze del settore pertinenti in {country}.
    IMPORTANTE: Il tuo rapporto finale DEVE essere scritto completamente in italiano, anche se le fonti che trovi sono in inglese o altre lingue. Traduci tutte le informazioni trovate.

  expected_output: >
    Un report completo in lingua italiana in formato markdown su {company}, che includa:
    - Una panoramica generale dell’azienda (indipendentemente dal paese)
    - I loro prodotti/servizi e la proposta di valore
    - Le loro attività specifiche in {country} (se presenti)
    - Tendenze rilevanti del settore in {country}
    - Considerazioni sulla cultura aziendale
  agent: research_agent

research_person_task:
  description: >
    Ricerca informazioni su {interviewer} con un focus sulla sua carriera professionale.
    Considera eventuali collegamenti con {country} o competenze regionali che potrebbe avere.
    IMPORTANTE: Il tuo rapporto finale DEVE essere scritto completamente in italiano.
  expected_output: >
    Un rapporto completo in lingua italiana in  formato markdown con punti elenco su {interviewer}.
  agent: research_agent

define_questions_task:
  description: >
    Definisci un elenco di domande in lingua italiana che un intervistatore dell'azienda {company} potrebbe fare ad un candidato per la posizione di {job_description}. Queste domande devono essere quelle che l'azienda farebbe al candidato durante un colloquio, NON domande che il candidato farebbe all'azienda.
    Basati sulla ricerca su {company}, sulla descrizione del lavoro {job_description}, 
    sull'intervistatore {interviewer} e considerando il contesto culturale di {country}.
    Considera le pratiche aziendali locali e le aspettative culturali in {country}.
  expected_output: >
    Un elenco di 20 domande che l'intervistatore potrebbe fare al candidato durante il colloquio, in formato Markdown. 
    Le domande dovrebbero coprire: Cultura e adattamento al Team, Adattamento alla Posizione di Lavoro, 
    Background e modalità di lavoro, Mentalità di Crescita e qualsiasi considerazione specifica del paese rilevante per {country}.
    Queste devono essere domande che l'AZIENDA farebbe AL CANDIDATO, non viceversa.
  agent: interview_coach
  context:
    - research_company_task
    - research_person_task
  output_file: output/domande_intervista.md

interview_prep_task:
  description: >
    Poni la seguente domanda all'utente e analizza la sua risposta:

    {job_position_report}
  expected_output: >
    La domanda posta e la risposta dell'utente.
  agent: interview_agent
  human_input: true

feedback_task:
  description: >
    Rivedi la risposta dell'utente alla domanda del colloquio:

    Domanda: {job_position_report}
    Risposta dell'utente: {user_answer}

    Fornisci un feedback costruttivo su:
    1. Cosa è stato buono nella risposta
    2. Cosa potrebbe essere migliorato
    3. Suggerimenti specifici per migliorare la risposta
    4. Modi alternativi per affrontare la domanda
  expected_output: >
    Feedback dettagliato sulla risposta dell'utente con punti specifici per il miglioramento e approcci alternativi.
  agent: interview_coach
  output_file: output/feedback.md
