research_company_task:
  description: >
    Research about {company}, their position in the sector and recent industry trends.
    Focus on recent news and developments from the last 12 months (from 2024 to 2025).
  expected_output: >
    A comprehensive report in markdown with bullet points about {company} and its industry.
  agent: research_agent

research_person_task:
  description: >
    Research about {interviewer} with a focus on their professional career.
  expected_output: >
    A comprehensive report in markdown with bullet points about {interviewer}.
  agent: research_agent

define_questions_task:
  description: >
    Define a list of questions based on the company {company}, job description {job_description}, 
    and interviewer {interviewer}.
  expected_output: >
    A list of 20 questions in Markdown format that cover: Culture and Team fit, Job Position Fit, 
    Background and ways of working, Growth Mindset.
  agent: interview_coach
  context:
    - research_company_task
    - research_person_task
  output_file: output/interview_questions.md

interview_prep_task:
  description: >
    Ask the following question to the user and analyze their response:

    {job_position_report}
  expected_output: >
    The question asked and the user's response.
  agent: interview_agent
  human_input: true

feedback_task:
  description: >
    Review the user's response to the interview question:

    Question: {job_position_report}
    User's Answer: {user_answer}

    Provide constructive feedback on:
    1. What was good about the answer
    2. What could be improved
    3. Specific suggestions to enhance the response
    4. Alternative ways to approach the question
  expected_output: >
    Detailed feedback on the user's answer with specific points for improvement and alternative approaches.
  agent: interview_coach
  output_file: output/feedback.md
